// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCThPKKxoYF_4PMORMeQjFpAubotI1FkxI',
    appId: '1:979560086593:web:739875cf22f83329bd9ac0',
    messagingSenderId: '979560086593',
    projectId: 'grad1-be41d',
    authDomain: 'grad1-be41d.firebaseapp.com',
    storageBucket: 'grad1-be41d.firebasestorage.app',
    measurementId: 'G-JRJ8K1LXHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCweIPbN0iOl-5s6NQoPB5ZuyLFExLBkEQ',
    appId: '1:979560086593:android:1effa0409854e172bd9ac0',
    messagingSenderId: '979560086593',
    projectId: 'grad1-be41d',
    storageBucket: 'grad1-be41d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKJ62YryFDV2MkALcZc2GG8go_4VkUNBg',
    appId: '1:979560086593:ios:b6700d4aa79ef146bd9ac0',
    messagingSenderId: '979560086593',
    projectId: 'grad1-be41d',
    storageBucket: 'grad1-be41d.firebasestorage.app',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKJ62YryFDV2MkALcZc2GG8go_4VkUNBg',
    appId: '1:979560086593:ios:b6700d4aa79ef146bd9ac0',
    messagingSenderId: '979560086593',
    projectId: 'grad1-be41d',
    storageBucket: 'grad1-be41d.firebasestorage.app',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCThPKKxoYF_4PMORMeQjFpAubotI1FkxI',
    appId: '1:979560086593:web:fa6d4a8c6b99c93cbd9ac0',
    messagingSenderId: '979560086593',
    projectId: 'grad1-be41d',
    authDomain: 'grad1-be41d.firebaseapp.com',
    storageBucket: 'grad1-be41d.firebasestorage.app',
    measurementId: 'G-QEPG2VF87D',
  );
}
